// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qmyqbyuoysubdnbydsik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteXFieXVveXN1YmRuYnlkc2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTQwODYsImV4cCI6MjA2NzMzMDA4Nn0.9by2ks6ZkR8UkccQUjlE1SDiqdtAn40WhH_6T3ixako";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);